FROM node:20

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .

RUN npm run build

# Install a static server
RUN npm install -g serve

EXPOSE 80

CMD ["serve", "-s", "build", "-l", "80"]
